name: Secret Scan with TruffleHog

on: 
  workflow_dispatch:

jobs :
  secret-scan:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Scan for secrets (TruffleHog)
        # uses: trufflesecurity/trufflehog@v3.90.5
        uses: trufflesecurity/trufflehog@main
        with:
          path: .
